### ISSUE TITLE
Hello, how do I deploy this website locally?

### ISSUE THREAD

**Issue by GaleaWong** [IBM/taxinomitis#49] opened 2018-07-12 15:31 UTC
I want to deploy the website locally, download the source code in GitHub, and I can't find "bluemix-autoscaling-agent" after NPM start.

**Comment by dalelane** [comment] 2018-07-12 17:14
Closing this as a duplicate of https://github.com/IBM/taxinomitis/issues/4 as I know I need to document how to run the app locally. Sorry, I've not had time to do that yet.

But to answer your specific question, you can use `npm run local` when you're running it outside of Bluemix.

**Closed by dalelane** 2018-07-12 17:14 UTC
