### ISSUE TITLE
How do I build my own ScratchX

### ISSUE THREAD

**Issue by GaleaWong** [IBM/taxinomitis#57] opened 2018-07-16 07:55 UTC
Find a lot of information do not know how to build their own ScratchX, please help me.

**Comment by dalelane** [comment] 2018-07-16 08:44
Closing this as a duplicate of https://github.com/IBM/taxinomitis/issues/4 as I know I need to document how to run the app locally. Sorry, I've not had time to do that yet. 

In the meantime, you could get it for yourself from https://github.com/LLK/scratchx

**Closed by dalelane** 2018-07-16 08:44 UTC
